### ISSUE TITLE
helloworld fails with unable to clone

### ISSUE THREAD

**Issue by axlroden** [flux-subsystem-argo/tf-controller-helloworld#1]
failed to checkout and determine revision: unable to clone 'https://github.com/axlroden/tf-controller-helloworld': couldn't find remote ref "refs/heads/HEAD"

I have this in my event log for the helloworld git repo, not sure whats wrong?

**Comment by chanwit** [comment]
I haven't been able to reproduce this behaviour. Would you try with revision: `main` instead of `HEAD` please?

**Comment by chanwit** [comment]
Oh I spot the error in the doc. Yeah I think I missed the step to use "main" instead of "HEAD" revision, so the doc bug bit you.

So sorry about that. I'll fix the doc, and thank you for reporting @axlroden !!

**Comment by chanwit** [comment]
Fixed by: https://github.com/flux-subsystem-argo/website/commit/3321a139aa4595addbe8949ce7a57b57b3253a2c

Please let me know if the problem still persists. Thank you.

**Comment by axlroden** [comment]
ah yes of course, main by default :)
